### ISSUE TITLE
Site works perfectly locally with hugo but on the webserver no design 

### ISSUE THREAD

**Issue by ghost** [posquit0/hugo-awesome-identity#16]
Hi,

I made my site on my local hugo server and it works perfect but if I compile the files and transfer it to the webserver I just have the text without any pictures / design..

Please follow this link: 
https://iamfromgermany.github.io/iamgerman.github.io/

How can I fix that?

Thanks,
Tim

**Comment by posquit0** [comment]
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1484002/110242089-b053c000-7f97-11eb-8089-67f73695f258.png">

I think you are not serving static files(images, css, etc) properly. Please check again your webserver configuration. :)
