### ISSUE TITLE
Issue with Hugo Server

### ISSUE THREAD

**Issue by AdeLouis** [posquit0/hugo-awesome-identity#2]
Hi! I really like your template and want to use it for my website. I follow all the directions but when I run "hugo server" I get an error that I am not sure how to fix. I have a screenshot below

![error](https://user-images.githubusercontent.com/17919698/60390267-d164cd80-9aa0-11e9-8ce2-567b8e37fd35.PNG)

**Comment by posquit0** [comment]
Could you check your Hugo version?

**Comment by AdeLouis** [comment]
Hi yes. The version I have is v.53 which I think is the current version that you have updates for. Is there an ideal version to use?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by posquit0** [comment]
Hmmm, I checked that I'm using hugo `v0.55.1` in my local environment. And when I tested with `hugo:0.53` docker image, I got the error message. Please try to use hugo `v0.55`. I'll update the minimum hugo version soon.

Thanks!

**Comment by AdeLouis** [comment]
So i tried with V0.55.1 and I still get a similar error. I used a different Hugo template from another user to make sure it wasn't just my computer and that one was successful. Not sure what to do.

![Capture](https://user-images.githubusercontent.com/17919698/60401449-a8e7dc80-9b4f-11e9-85b2-332f804453c0.PNG)

**Comment by posquit0** [comment]
I found the reason for your problem. Compiling SCSS needs the extended version of Hugo. Please check the following link:

- [Hugo FAQ](https://gohugo.io/troubleshooting/faq/#i-get-tocss-this-feature-is-not-available-in-your-current-hugo-version)

**Comment by posquit0** [comment]
Let me know if you solve this problem! :)

**Comment by AdeLouis** [comment]
It solved it. Thank you so much. I am currently creating mine! One question though, how did you include the links on your website that links to your resume and stuff. 

All the best

**Comment by posquit0** [comment]
You can check the example project here:
https://github.com/posquit0/identity

Good luck!
